<%@ Page Title="" Language="C#" MasterPageFile="~/f6761_MasterExample.master" AutoEventWireup="true" CodeFile="f6761_Autokauppa.aspx.cs" Inherits="f6761_Autokauppa" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server" >

    <div class="row">
        <div class="col-md-5">
        <h2>Autot kannassa</h2>
    <asp:GridView ID="GridView1"  runat="server" AllowSorting="True" 
        OnRowDeleting="GridView1_RowDeleting" OnSorting="GridView1_Sorting" AutoGenerateDeleteButton="True">
        
    </asp:GridView>

        </div>

        <div class="col-md-6">
                    
            
        <h2>Lisää uusi auto </h2>
            <asp:Label ID="Label1" runat="server" Text="Auto ID"></asp:Label> <br />
            <asp:TextBox ID="txtAid" runat="server"></asp:TextBox> <asp:RequiredFieldValidator ID="RequiredFieldValidator1" ControlToValidate="txtAid" runat="server" ErrorMessage="TYHJÄ"></asp:RequiredFieldValidator> <br />
            <asp:Label ID="Label2" runat="server" Text="Auton rekisterinumero"></asp:Label> <br />
            <asp:TextBox ID="txtRekkari" runat="server"></asp:TextBox> <asp:RequiredFieldValidator ID="RequiredFieldValidator2" ControlToValidate="txtRekkari" runat="server" ErrorMessage="TYHJÄ"></asp:RequiredFieldValidator><br />
            <asp:Label ID="Label3" runat="server" Text="Merkki"></asp:Label><br />
            <asp:TextBox ID="txtMerkki" runat="server"></asp:TextBox> <asp:RequiredFieldValidator ID="RequiredFieldValidator3" ControlToValidate="txtMerkki" runat="server" ErrorMessage="TYHJÄ"></asp:RequiredFieldValidator><br />
            <asp:Label ID="Label4" runat="server" Text="Malli"></asp:Label><br />
            <asp:TextBox ID="txtMalli" runat="server"></asp:TextBox> <asp:RequiredFieldValidator ID="RequiredFieldValidator4" runat="server" ControlToValidate="txtMalli" ErrorMessage="TYHJÄ"></asp:RequiredFieldValidator><br />
            <asp:Label ID="Label5" runat="server" Text="Vuosimalli"></asp:Label><br />
            <asp:TextBox ID="txtVm" runat="server"></asp:TextBox> <asp:RequiredFieldValidator ID="RequiredFieldValidator5" runat="server" ControlToValidate="txtVm" ErrorMessage="TYHJÄ"></asp:RequiredFieldValidator><br />
            <asp:Label ID="Label6" runat="server" Text="Myynti hinta"></asp:Label><br />
            <asp:TextBox ID="txtMyyntiHinta" runat="server"></asp:TextBox> <asp:RequiredFieldValidator ID="RequiredFieldValidator6" runat="server" ControlToValidate="txtMyyntiHinta" ErrorMessage="TYHJÄ"></asp:RequiredFieldValidator><br />
            <asp:Label ID="Label7" runat="server" Text="Sisäänostohinta"></asp:Label><br />
            <asp:TextBox ID="txtSisaanOstoHinta" runat="server"></asp:TextBox> <asp:RequiredFieldValidator ID="RequiredFieldValidator7" runat="server" ControlToValidate="txtSisaanOstoHinta" ErrorMessage="TYHJÄ"></asp:RequiredFieldValidator><br />
            <asp:Button ID="btnUusiAuto" runat="server" Text="Tee uusi auto" OnClick="btnUusiAuto_Click" /><br /><br /><br />

            <asp:Label ID="log" runat="server" Text="Et ole kirjautunut sisään"></asp:Label>
            <asp:Button ID="btnLogin" runat="server" Text="Kirjaudu sisään" OnClick="btnLogin_Click" CausesValidation="false" />

    </div>
    
    </div>
    
       
</asp:Content>

