//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class lasnaolot
{
    public short id { get; set; }
    public string asioid { get; set; }
    public string lastname { get; set; }
    public string firstname { get; set; }
    public Nullable<System.DateTime> date { get; set; }
    public string course { get; set; }
    public byte[] added { get; set; }
    public Nullable<System.DateTime> dateAdded { get; set; }
}
